### ISSUE TITLE
Multiserver: page not reachable

### ISSUE THREAD

**Issue by TheStraing** [cj123/assetto-server-manager#669] opened 2019-12-03 11:53 UTC
Hi, I created 3 server with the new multiserver setup but after a while I got these errors

![image](https://user-images.githubusercontent.com/16732179/70048911-b5270880-15cb-11ea-93a6-2dd170fbc2c1.png)

![image](https://user-images.githubusercontent.com/16732179/70048895-adfffa80-15cb-11ea-8a6b-963bba1999f3.png)

**Comment by TheStraing** [comment] 2019-12-03 12:01
I tried to increase the max file descriptors from 1024 to 2048 to see If I get the same error... I'll let you know

**Comment by TheStraing** [comment] 2019-12-06 19:52
Ok, after 3 days of uptime I got the same problem again

![image](https://user-images.githubusercontent.com/16732179/70351931-4ca98700-186a-11ea-9975-d68562fec1d5.png)

**Comment by cj123** [comment] 2019-12-07 13:39
Hey - Could you provide a bit more information about the machine that you're running on (OS/specs)?

I think there's some code changes that can be made here to improve the multiserver tool, and maybe further configuration changes too.

**Comment by TheStraing** [comment] 2019-12-07 13:42
It's a AWS EC2 Instance with Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1054-aws x86_64).
There are multiple servers (nodejs,nginx,etc) running on the same machine.
It should have 2 Gb of Ram if I remember correctly.

**Comment by cj123** [comment] 2019-12-07 13:45
I'll see if I can put some better handling of HTTP connections into the next release of our multiserver release tool, and do some testing in a similar scenario.

**Comment by cj123** [comment] 2019-12-17 16:45
I can confirm that I've figured out the cause of this, and it will be released with 1.6.1 this week.

**Closed by cj123** 2019-12-17 16:45 UTC
