### ISSUE TITLE
Results with error

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#388] opened 2019-06-21 18:31 UTC
Same race, different result.

The correct is this 👍 
![image](https://user-images.githubusercontent.com/48275749/59943562-f0c48080-9438-11e9-8795-e604b5d43b5c.png)

and the bad is this:
![image](https://user-images.githubusercontent.com/48275749/59943633-1d789800-9439-11e9-8baa-a18c57c8e4d4.png)

Here the link:
http://clubcsr.ddns.net:8776/results/2019_6_21_0_24_RACE

and here the log: (link)
https://drive.google.com/open?id=1t5bej20VCc1qU3ngoTYjGM6DNFhtnS4C

Can you help me?

Thanks in advance

**Comment by cj123** [comment] 2019-06-22 15:34
Hi Luis, this is very strange indeed. We'll try get this sorted for the next update if we can.

**Comment by cj123** [comment] 2019-06-22 16:24
@luismercury i've been thinking about this some more - trying to figure out where the strange ordering might have come from. Did you apply any penalties at any point to these results? (Even if you removed them afterwards)

**Comment by luismercury** [comment] 2019-06-23 01:21
No.
We don't use penalties.

**Comment by luismercury** [comment] 2019-06-24 03:58
I created a new event and then I imported the json .... same result.

**Comment by cj123** [comment] 2019-06-24 15:28
@luismercury do you use any assetto corsa server plugins? KMR, stracker, etc?

**Comment by luismercury** [comment] 2019-06-25 03:25
No.

Do you like file json?

**Comment by luismercury** [comment] 2019-06-28 17:57
more forensic data.....

http://simresults.net/remote?result=http://clubcsr.ddns.net:8776/results/download/2019_6_21_0_24_RACE.json

Lap 15 is correct and race finish.
Lap 16???? wrong....here the problem.


![image](https://user-images.githubusercontent.com/48275749/60361230-0f37f800-99b4-11e9-80a2-30e358a7541b.png)

more...
The winner is Joaquin Rossi Silva but He is 19....the problem is lap 16
![image](https://user-images.githubusercontent.com/48275749/60361501-b452d080-99b4-11e9-986a-163fa92a672f.png)

**Comment by luismercury** [comment] 2019-07-10 12:50
1- This result is correct (with entry list no guid id)
http://clubcsr.ddns.net:8776/results/2019_7_9_22_44_RACE

2- Result with error (We use Booking)
http://clubcsr.ddns.net:8776/results/2019_7_9_23_34_RACE

if you click on "Nico Capalbo" he says that his final result was 3 (It's correct)

if you click on "Dino Sassone" he says that his final result was 1 (It's correct)

and so with each drivers.

I believe that the final building of the result has an error.

Is someone else suffering from this error with event Booking?

# Name Team Car Total Race Time Num Laps Best Lap Average Clean Lap Handicaps Crashes 
1 Nico Capalbo Ferrari 488 GT3 CSR 2m24.252s 8 laps / 0 cuts 2m24.251s
Tyre: M 2m3.924s 

n/a 0 
2 Raul Garcia Ferrari 488 GT3 CSR 16m5.12s 8 laps / 0 cuts 2m4.207s
Tyre: M 2m6.43s 

n/a 4 
3 Luis Mercury Ferrari 488 GT3 CSR 16m33.795s 8 laps / 0 cuts 2m1.661s
Tyre: M 2m6.153s 

n/a 4 
4 Matias Corvino Ferrari 488 GT3 CSR 16m36.125s 8 laps / 0 cuts 2m1.373s
Tyre: M 2m3.832s 

n/a 0 
5 Dino Sassone Ferrari 488 GT3 CSR 16m46.578s 8 laps / 0 cuts 2m3.234s
Tyre: M 2m3.367s 

n/a 10

**Comment by cj123** [comment] 2019-07-10 12:53
This is a really strange one - we haven't seen it happen anywhere at all, but we don't use Booking sessions. I'll try and do a test with a Booking session and see if it happens. Does it happen every event that you do which has a booking session?

**Comment by luismercury** [comment] 2019-07-10 14:03
I'm trying to associate some pattern.
One can be the booking.
because it is taking place in these circumstances.

It's to emphasize that CM gets the data well.
![image](https://user-images.githubusercontent.com/48275749/60975280-1b9c4900-a302-11e9-960f-0c8b7e9973d2.png)

**Comment by cj123** [comment] 2019-07-26 10:59
@luismercury I think that this ended up being caused by the extra lap your drivers were doing? Is that correct?

Either way I don't think this is a Server Manager issue...

**Comment by cj123** [comment] 2019-08-05 21:19
fixed by @Hecrer in #453

**Closed by cj123** 2019-08-05 21:19 UTC
Labels: bug, can't reproduce, help wanted
