### ISSUE TITLE
Option for hiding specific pages to the public?

### ISSUE THREAD

**Issue by WraithStar** [cj123/assetto-server-manager#353] opened 2019-05-27 14:56 UTC
If you make the Server Manager visible to the public, that makes some of the pages from "Content", "Server Logs", "Championships" and "Server" tabs available to the public, without having to log in.

This is the only option you have if you want to provide a publicly accessible live timing page.

Some server admins tho might not want to show such pages to the public, especially the one about server logs. Content tab might be unnecessary as well, since it allows anyone to download custom setups from the car pages

**Comment by cj123** [comment] 2019-05-27 15:00
I believe that this nicely hooks into #261. Under the improved system, it will be possible to remove those pages from the 'read' group, hence removing them from public availability.

For the moment, if you wanted to restrict certain pages, you could use a reverse proxy with HTTP Basic Auth to restrict all pages except live timings to a passworded user. (Though I understand this isn't ideal.)

I think we're currently planning for the permissions ticket to be fixed in [v1.4](https://github.com/cj123/assetto-server-manager/milestone/3)

**Comment by cj123** [comment] 2019-08-21 14:51
Closing as duplicate of #261

**Closed by cj123** 2019-08-21 14:51 UTC
