### ISSUE TITLE
Restart - Doesn't read the new parameters

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#420] opened 2019-07-10 14:45 UTC
Restart - Doesn't read the new parameters.

Eg. I modified number of slots and restart doesn't read the new parameters.
was necessary to stop the server and then restart

![image](https://user-images.githubusercontent.com/48275749/60978174-21485d80-a307-11e9-99a3-01eab8fb770e.png)
![image](https://user-images.githubusercontent.com/48275749/60978589-c105eb80-a307-11e9-9ddd-12366e6952f3.png)

Is it possible to put the "stop button" here?

![image](https://user-images.githubusercontent.com/48275749/60978809-1510d000-a308-11e9-822d-4482e6907ddc.png)

**Comment by cj123** [comment] 2019-07-10 14:51
Hi Luis,

"Restart" not changing things is actually how we intend for it to work. Restart literally just restarts the assetto process. It doesn't change config files or do anything else. If you want to start an event after you have edited it, you must click 'Start Race' again and it will set it up with the new options you have changed.

As for putting a stop button in, this would be a lot of work for something that already exists in the server process management. We would have to detect which of the current events is running and then only show the stop button on the page for that event, which I think would also look messy too.

Closing this as working as intended.

**Closed by cj123** 2019-07-10 14:51 UTC
